### ISSUE TITLE
element-ui的table表格控件表头与内容列不对齐的问题

### ISSUE THREAD

**Issue by madfour** [madfour/blog-docs#45]
## element-ui的table表格控件表头与内容列不对齐问题
![捕获](https://user-images.githubusercontent.com/29498303/113237265-1acaf800-92d9-11eb-8516-cd109a3daa1d.PNG)

## 解决方法：
将以下样式代码添加到index.html、或app.vue中（必须是入口文件，起全局作用！）
```css
/* 解决element-ui的table表格控件表头与内容列不对齐问题 */

.el-table th.gutter{

    display: table-cell!important;

}
```
